### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by behnam-yousefi** [drieslab/GiottoUtils#37]
When I try to install
```
devtools::install_github('drieslab/GiottoUtils')
```
I get the error below
```
Error: object ‘assert_permutation’ is not exported by 'namespace:checkmate'
```
the version of my ```checkmate``` is *2.1.0*.

P.S. I am actually trying to install 
```
devtools::install_github("drieslab/Giotto@suite")
```
and I get the error related to ```GiottoUtils```.
```
ERROR: dependency ‘GiottoUtils’ is not available for package ‘GiottoClass’
```

**Comment by RubD** [comment]
@jiajic do we need to specify the minimum checkmate version?

**Comment by jiajic** [comment]
Hi, sorry for the last reply. I'm working on a set of updates that should fix this issue.

**Comment by jiajic** [comment]
This should be fixed now. Thank you for reporting.
